config/routes.rb
Rails.application.routes.draw do

   root 'ideas#index'

  resources :ideas
  get 'about' => 'static_pages#about'
  get 'random' => 'static_pages#random'

end

app/models/idea.rb
class Idea < ActiveRecord::Base
    validates :description, :author, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
    def index
        @ideas = Idea.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
    end
    
    def create
        @idea = Idea.create(idea_params)
        redirect_to root_path
    end
    
    def edit
        @idea = Idea.find(params[:id])
    end
    
    def update
        @idea = Idea.find(params[:id])
        if @idea.update(idea_params)
            redirect_to root_path
        else
            redirect_to edit_idea_path(params[:id])
        end
    end
    
    def destroy
        @idea = Idea.find(params[:id])
        @idea.destroy
        redirect_to root_path
    end

    private
    
    def idea_params
        params.require(:idea).permit(:description, :author)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def about
        
    end
    
    def random
        @idea = Idea.order("RANDOM()").first
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/ideas/edit.html.erb
<h1>Revise Idea</h1>

<%= simple_form_for @idea, method: :patch do |f| %>
    <%= f.input :description %>
    <%= f.input :author %>
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/ideas/index.html.erb
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Add Idea
</button>


<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
           <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
           <h4 class="modal-title" id="myModalLabel">Modal title</h4>
        </div>
      <%= simple_form_for Idea.new do |f| %>
        <div class="modal-body">
            <%= f.input :description %>
            <%= f.input :author %>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit 'Submit', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<br><br>

<% @ideas.each do |idea| %>
    <div class="panel panel-default">
      <div class="panel-body">
        <blockquote>
            <p><%= idea.description %></p>
            <small><%= idea.author %></small>
        </blockquote>
        <br>
        <div class="btn-group" role="group">
         <%= link_to 'Delete', idea_path(idea), method: :delete, class: 'btn btn-sm btn-danger', data: {confirm: "Are you sure?"} %>
         <%= link_to 'Revise', edit_idea_path(idea), class: 'btn btn-sm btn-success' %>
        </div> 
      </div>
    </div>

<% end %>

<div class = "text-center">
  <%= will_paginate @ideas %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Anton|Gloria+Hallelujah|Kaushan+Script|Lobster|Permanent+Marker&effect=brick-sign|crackle|vintage|wallpaper" rel="stylesheet">
</head>
<body>
<div class = "wrap">
  <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><div class="font-effect-crackle">Ideator</div></a>
        </div>
  
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'All Ideas', root_path %></li>
            <li><%= link_to 'Inspire Me', random_path %></li>
            <li><%= link_to 'About', about_path %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  
  <div class = "container">
    <%= yield %>
  </div>
</div>
<footer class="footer text-center">
  <div class="container">
    <div class = "row">
      <div class = "col-xs-12 col-md-4">
        <h4><i class="fa fa-pencil" aria-hidden="true"></i> Contact</h4>
        <p>contact@techrise.me</p>
      </div>
      <div class = "col-xs-12 col-md-4">
        <h4><i class="fa fa-rocket" aria-hidden="true"></i> Find Us</h4>
        <div class="social-buttons">
          <a href = "#"><i class="fa fa-facebook-official social" ></i></a>
          <a href = "#"><i class="fa fa-twitter-square social" ></i></a>
          <a href = "#"><i class="fa fa-linkedin-square social" ></i></a>
        </div>
      </div>
      <div class = "col-xs-12 col-md-4">
        <h4><i class="fa fa-eject" aria-hidden="true"></i> © TECHRISE 2016</h4>
        <p>All Rights Reserved</p>
      </div>
    </div>
  </div>
</footer>

</body>
</html>

app/views/static_pages/about.html.erb
<h1>About</h1>

<h4>Share your ideas with the world and find others</h4>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla, quisquam ducimus officiis id officia. Pariatur, laborum, explicabo recusandae et vero fugiat blanditiis ea dolorum nam maiores dignissimos similique nesciunt. Porro.</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum, inventore tempore nam voluptate doloremque soluta quos animi rerum placeat quas et libero pariatur illo corporis odio a beatae natus vero!</p>

app/views/static_pages/random.html.erb
<% if @idea.present? %>
<%= link_to 'Inspire Me', random_path, class: 'btn btn-primary btn-block' %>

<div class="panel panel-default">
      <div class="panel-body">
        <blockquote>
            <p><%= @idea.description %></p>
            <small><%= @idea.author %></small>
        </blockquote>
        <br>
        <div class="btn-group" role="group">
         <%= link_to 'Delete', idea_path(@idea), method: :delete, class: 'btn btn-sm btn-danger', data: {confirm: "Are you sure?"} %>
         <%= link_to 'Revise', edit_idea_path(@idea), class: 'btn btn-sm btn-success' %>
        </div> 
      </div>
    </div>
    
    <h4>No ideas have been shared. Add one <%= link_to 'here', root_path %></h4>
    
<% end %>
    